export const quotes = [
  { text: "Success usually comes to those who are too busy to be looking for it." },
  { text: "Don’t be afraid to give up the good to go for the great." },
  { text: "Success is the sum of small efforts repeated day in and day out." },
  { text: "Opportunities don't happen. You create them." },
  { text: "The road to success and the road to failure are almost exactly the same." },
  { text: "Life is 10% what happens to us and 90% how we react to it." },
  { text: "Life isn’t about finding yourself. Life is about creating yourself." },
  { text: "Don’t count the days, make the days count." },
  { text: "In the end, we only regret the chances we didn’t take." },
  { text: "Life is really simple, but we insist on making it complicated." },
  { text: "Happiness is not something ready made. It comes from your own actions." },
  { text: "For every minute you are angry you lose sixty seconds of happiness." },
  { text: "The happiest people don’t have the best of everything, they make the best of everything." },
  { text: "Happiness depends upon ourselves." },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears." },
  { text: "The future depends on what you do today." },
  { text: "Believe you can and you're halfway there." },
  { text: "Don’t stop when you’re tired. Stop when you’re done." },
  { text: "Push yourself, because no one else is going to do it for you." },
  { text: "Do something today that your future self will thank you for." },
  { text: "It does not matter how slowly you go as long as you do not stop." },
  { text: "Fall seven times, stand up eight." },
  { text: "When you feel like quitting, think about why you started." },
  { text: "Perseverance is not a long race; it's many short races one after the other." },
  { text: "A river cuts through rock not because of its power, but because of its persistence." },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you." },
  { text: "Positive anything is better than negative nothing." },
  { text: "Stay positive, work hard, make it happen." },
  { text: "Wherever you go, no matter what the weather, always bring your own sunshine." },
  { text: "Be the energy you want to attract." }
]
