export const quotes = [
  { text: "Hi!  I'm Mania Shakeel  — I made this just for you." },
  {text: "Success usually comes to those who are too busy to be looking for it." },
  { text: "Don’t be afraid to give up the good to go for the great." },
  { text: "Success is the sum of small efforts repeated day in and day out." },
  { text: "Opportunities don't happen. You create them." },
  { text: "The road to success and the road to failure are almost exactly the same." },
  { text: "Life is 10% what happens to us and 90% how we react to it." },
  { text: "Life isn’t about finding yourself. Life is about creating yourself." },
  { text: "Don’t count the days, make the days count." },
  { text: "In the end, we only regret the chances we didn’t take." },
  { text: "Life is really simple, but we insist on making it complicated." },
  { text: "Happiness is not something ready made. It comes from your own actions." },
  { text: "For every minute you are angry you lose sixty seconds of happiness." },
  { text: "The happiest people don’t have the best of everything, they make the best of everything." },
  { text: "Happiness depends upon ourselves." },
  { text: "Count your age by friends, not years. Count your life by smiles, not tears." },
  { text: "The future depends on what you do today." },
  { text: "Believe you can and you're halfway there." },
  { text: "Don’t stop when you’re tired. Stop when you’re done." },
  { text: "Push yourself, because no one else is going to do it for you." },
  { text: "Do something today that your future self will thank you for." },
  { text: "It does not matter how slowly you go as long as you do not stop." },
  { text: "Fall seven times, stand up eight." },
  { text: "When you feel like quitting, think about why you started." },
  { text: "Perseverance is not a long race; it's many short races one after the other." },
  { text: "A river cuts through rock not because of its power, but because of its persistence." },
  { text: "Keep your face always toward the sunshine—and shadows will fall behind you." },
  { text: "Positive anything is better than negative nothing." },
  { text: "Stay positive, work hard, make it happen." },
  { text: "Wherever you go, no matter what the weather, always bring your own sunshine." },
  { text: "Be the energy you want to attract." },
  { text: "Happiness is not by chance, but by choice." },
  { text: "Joy is the simplest form of gratitude." },
  { text: "The happiest people don’t have the best of everything, they make the best of everything." },
  { text: "Tears water the growth of your soul." },
  { text: "It’s okay to fall apart sometimes; tacos fall apart, and we still love them." },
  { text: "Sadness is but a wall between two gardens." },
  { text: "Discipline is choosing between what you want now and what you want most." },
  { text: "The only limit is the one you set yourself." },
  { text: "Dream big, start small, act now." },
  { text: "Your only competition is the person you were yesterday." },
  { text: "Education is the passport to the future." },
  { text: "Learning is a treasure that follows its owner everywhere." },
  { text: "The mind is not a vessel to be filled, but a fire to be kindled." },
  { text: "You are braver than you believe, stronger than you seem, and smarter than you think." },
  { text: "Doubt kills more dreams than failure ever will." },
  { text: "The worst enemy to creativity is self-doubt." },
  { text: "Strength doesn’t come from what you can do; it comes from overcoming the things you once thought you couldn’t." },
  { text: "A diamond is just a piece of charcoal that handled stress exceptionally well." },
  { text: "You never know how strong you are until being strong is your only choice." },
  { text: "Smooth seas never made skilled sailors." },
  { text: "The oak fought the wind and was broken; the willow bent when it must and survived." },
  { text: "Rock bottom became the solid foundation on which I rebuilt my life." },
  { text: "Courage is resistance to fear, mastery of fear—not absence of fear." },
  { text: "Fear is a reaction. Courage is a decision." },
  { text: "Be fearless in the pursuit of what sets your soul on fire." },
  { text: "The only true wisdom is in knowing you know nothing." },
  { text: "Knowledge speaks, but wisdom listens." },
  { text: "A wise man learns more from his enemies than a fool from his friends." },
  { text: "Tears are words the heart can't express." },
{ text: "Sorrow prepares you for joy." },
{ text: "Grief is the price we pay for love." },
{ text: "What we once enjoyed and deeply loved we can never lose." },
{ text: "Giving up is the only sure way to fail." },
{ text: "Never give up on a dream just because of the time it will take to accomplish it." },
{ text: "Consistency is what transforms average into excellence." },
{ text: "Small disciplines repeated with consistency every day lead to great achievements." },
{ text: "The most common way people give up their power is by thinking they don’t have any." },
{ text: "With great power comes great responsibility." },
{ text: "He who cannot command himself cannot command others." },
{ text: "To command is to serve, nothing more and nothing less." },
{ text: "Success doesn’t just find you. You have to go out and get it." },
{ text: "Dream big and dare to fail." },
{ text: "You never know how strong you are until being strong is your only choice." },
{ text: "Strength does not come from winning. Your struggles develop your strengths." },
{ text: "Courage doesn’t always roar. Sometimes courage is the quiet voice at the end of the day saying, 'I will try again tomorrow.'" },
{ text: "It takes courage to grow up and become who you really are." },
{ text: "Hope is being able to see that there is light despite all of the darkness." },
{ text: "Once you choose hope, anything’s possible." },
{ text: "Knowing yourself is the beginning of all wisdom." },
{ text: "Wisdom is the reward you get for a lifetime of listening when you’d have preferred to talk." },
{ text: "The difference between the impossible and the possible lies in a person’s determination." },
{ text: "A dream doesn’t become reality through magic; it takes sweat, determination, and hard work." },
{ text: "Resilience is accepting your new reality, even if it’s less good than the one you had before." },
{ text: "Out of difficulties grow miracles." },
{ text: "Discipline is the bridge between goals and accomplishment." },
{ text: "Dream big. Start small. Act now." },
{ text: "The harder you work for something, the greater you’ll feel when you achieve it." },
{ text: "Success is not for the lazy." },
{ text: "Your mindset determines your future." },
{ text: "Great things never come from comfort zones." },
{ text: "You don’t have to be great to start, but you have to start to be great." },
{ text: "Work hard in silence. Let your success be your noise." },
{ text: "Don’t wish for it. Work for it." },
{ text: "Success starts with self-discipline." },
{ text: "Hustle until your haters ask if you’re hiring." },
{ text: "Small steps every day lead to big results." },
{ text: "Your only limit is your mind." },
{ text: "You become what you believe." },
{ text: "Clarity of vision brings clarity of results." },
{ text: "Every accomplishment starts with the decision to try." },
{ text: "The key to success is to focus on goals, not obstacles." },
{ text: "Winners train. Losers complain." },
{ text: "A strong mind builds a strong life." },
{ text: "You are stronger than your excuses." },
{ text: "Let your hustle be louder than your fears." },
{ text: "Turn your pain into power." },
{ text: "Make it happen. Shock everyone." },
{ text: "Success doesn't come from what you do occasionally, but what you do consistently." },
{ text: "Focus on the step in front of you, not the whole staircase." },
{ text: "You’re only one decision away from a totally different life." },
{ text: "Energy flows where attention goes." },
{ text: "Train your mind to see the good in everything." },
{ text: "Don’t downgrade your dream to fit your reality. Upgrade your mindset." },
{ text: "Grind now. Greatness later." },
{ text: "Pride is not the opposite of shame, but its source. True humility is the only antidote to shame." },
{ text: "Ego is the anesthesia that deadens the pain of stupidity." },
{ text: "Pride makes us artificial and humility makes us real." },
{ text: "Too much pride will kill you, but too much humility will destroy you." },
{ text: "Ego is the enemy of what you want and of what you have: of mastering a craft, of real creative insight, of working well with others." },
{ text: "Pride is holding your head up when everyone around you is bowing theirs." },
{ text: "Ego is the source of all problems." },
{ text: "Pride is concerned with who is right. Humility is concerned with what is right." },
{ text: "A proud man is always looking down on things and people; and, of course, as long as you are looking down, you cannot see something that is above you." },
{ text: "Ego is the only requirement to destroy any relationship." },
{ text: "The great aim of education is not knowledge but action." },
{ text: "If you are determined to learn, no one can stop you." },
{ text: "Education is the passport to the future, for tomorrow belongs to those who prepare for it today." },
{ text: "Curiosity is the wick in the candle of learning." },
{ text: "Education is the movement from darkness to light." },
{ text: "Learning is the cornerstone of growth; it empowers us to shape our futures." },
{ text: "You don’t learn to walk by following rules. You learn by doing, and by falling over." },
{ text: "The purpose of learning is growth, and our minds can continue growing as we live." },
{ text: "Teachers open the door, but you must enter by yourself." },
{ text: "Live as if you were to die tomorrow. Learn as if you were to live forever." },
{ text: "The more that you read, the more things you will know." },
{ text: "Education is the ability to listen to almost anything without losing your temper or self-confidence." },
{ text: "Learning is not attained by chance; it must be sought with ardor and diligence." },
{ text: "The expert in anything was once a beginner." },
{ text: "A person who won’t read has no advantage over one who can’t read." },
{ text: "Change is the end result of all true learning." },
{ text: "Success comes in cans, failure in can’ts." },
{ text: "You are always a student, never a master. You have to keep moving forward." },
{ text: "The whole purpose of education is to turn mirrors into windows." },
{ text: "Develop a passion for learning. If you do, you will never cease to grow." },
{ text: "One hour per day of study in your chosen field will put you at the top within years." },
{ text: "There is no end to education. The whole of life is a process of learning." },
{ text: "The mind is not a vessel to be filled but a fire to be ignited." },
{ text: "Learning never exhausts the mind." },
{ text: "Education is not the filling of a pail, but the lighting of a fire." },
{ text: "Health is wealth." },
{ text: "Fitness is a journey, not a destination." },
{ text: "Your body deserves the best." },
{ text: "Strong body, strong mind." },
{ text: "Wealth grows from smart choices." },
{ text: "Money talks, wealth whispers." },
{ text: "Save money, live better." },
{ text: "Invest in yourself first." },
{ text: "Good health fuels success." },
{ text: "Fitness is the best medicine." },
{ text: "Wealth is the ability to fully experience life." },
{ text: "Money is a tool, not a goal." },
{ text: "Healthy habits build a healthy life." },
{ text: "Fitness is freedom." },
{ text: "Build wealth, not debt." },
{ text: "Money without health is meaningless." },
{ text: "Strong habits create strong results." },
{ text: "Health is the real currency." },
{ text: "Wealth is earned, not given." },
{ text: "Your health is your true wealth." }
]